redis_server:  Fix Py3 str/bytes problem
    Traceback (most recent call last):
      File "[...]/redis_store/redis_server", line 148, in <module>
        server = RedisServer()
      File "[...]/redis_store/redis_server", line 62, in __init__
        self._check_if_redis_server_is_installed()
      File "[...]/redis_store/redis_server", line 86, in _check_if_redis_server_is_installed
        match = re.search(r'.*v=(\d+\.\d+\.\d+) .*', redisv)
      File "/usr/lib/python3.8/re.py", line 199, in search
        return _compile(pattern, flags).search(string)
    TypeError: cannot use a string pattern on a bytes-like object

    Traceback (most recent call last):
      File "[...]/redis_store/scripts/redis_server", line 148, in <module>
        server = RedisServer()
      File "[...]/redis_store/scripts/redis_server", line 66, in __init__
        self._server_loop()
      File "[...]/redis_store/scripts/redis_server", line 124, in _server_loop
        if 'ERROR' in stdout:
    TypeError: a bytes-like object is required, not 'str'